version: '3.1'
services:
  db:
    container_name: issuetracker-db
    build:
      context: .
      dockerfile: docker/db/Dockerfile

  api:
    container_name: issuetracker-api
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    depends_on:
      - db
